import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import period from "../admin/schemas/period";
import { getAllDiscs, getAllPeriods } from "../data";
import styles from "../styles/Home.module.scss";

export default function Home({ periods }) {
  return (
    <div>
      <Head>
        <title>A Murmuration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[210px] mx-5 border-l-[1px] border-solid border-saddle">
        <div className="ml-[12px] snap-y snap-mandatory">
          {periods.map((period, key) => (
            <div key={key} className="flex items-center snap-center">
              <span className="w-3 h-3 bg-platinum border-solid border-[1px] border-saddle rounded-full ml-[-18px] mt-[-12px]"></span>
              <div className="inline-block text-7xl pl-1 tracking-[-0.07em] text-saddle">
                {period.Period}
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const periods = await getAllPeriods();
  return {
    props: { periods },
    revalidate: 10,
  };
}
